
#define voltage PC0

#define BALL_NUM 16
#define LINE_NUM 41
#define LINE_FRONTNUM 10
#define LINE_REARNUM 9
#define LINE_LEFTNUM 14
#define LINE_RIGHTNUM 8
#define LINE_FRONTEDGENUM 0
#define LINE_REAREDGENUM 0
#define LINE_LEFTEDGENUM 0
#define LINE_RIGHTEDGENUM 0
#define LINE_FRONTINSIDENUM 0
#define LINE_REARINSIDENUM 0
#define LINE_LEFTINSIDENUM 0
#define LINE_RIGHTINSIDENUM 0
#define LED_STRIP 16
#define LED_FRONT 13
#define LED_REAR 14
#define LED_LEFT 12
#define LED_RIGHT 12

#define LED_PIN_T PB6
#define LED_PIN_F PB7
#define LED_PIN_L PA15
#define LED_PIN_B PC1
#define LED_PIN_R PB1

#define LCD_INTERVAL 300

#define UI_ADDRESS 0x04
#define LINE_FRONTADDRESS 0x08
#define LINE_REARADDRESS 0x20
#define LINE_LEFTADDRESS 0x10
#define LINE_RIGHTADDRESS 0x40

#define LINE_BRIGHTNESS 255  // 50
#define NEOPIXEL_BRIGHTNESS 30
#define LIGHTLIMIT 0
#define LINEOVERTIME 500